---
- name: Install LAMP stack on Ubuntu
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present
  - name: Start Apache and enable it at boot
    service:
      name: apache2
      state: started
      enabled: yes
  - name: Install MySQL
    apt:
      name: mysql-server
      state: present
  - name: Start MySQL and enable it at boot
    service:
      name: mysql
      state: started
      enabled: yes
  - name: Install PHP
    apt:
      name: php
      state: present
  - name: Install PHP modules required for LAMP
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php-mysql
      - libapache2-mod-php
      - php-curl
      - php-gd
      - php-intl
      - php-mbstring
      - php-xml
      - php-zip
#      
# Run the playbook with the following:
# ansible-playbook lamp-ubuntu.yml
#